using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniLibrary.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixAuthorsAndBooksRelationship : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create Authors table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Authors"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(100) NOT NULL,
                    ""Nationality"" text NOT NULL,
                    ""BirthDate"" timestamp with time zone NOT NULL,
                    ""Biography"" text NOT NULL,
                    CONSTRAINT ""PK_Authors"" PRIMARY KEY (""Id"")
                );
            ");

            // Create default author if Authors table is empty
            migrationBuilder.Sql(@"
                INSERT INTO ""Authors"" (""Name"", ""Nationality"", ""BirthDate"", ""Biography"")
                SELECT 'Unknown Author', 'Unknown', '1900-01-01', 'Default author for existing books'
                WHERE NOT EXISTS (SELECT 1 FROM ""Authors"");
            ");

            // Add AuthorId column if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'Books' AND column_name = 'AuthorId'
                    ) THEN
                        ALTER TABLE ""Books"" ADD COLUMN ""AuthorId"" integer;
                    END IF;
                END $$;
            ");

            // Update existing books to reference default author
            migrationBuilder.Sql(@"
                UPDATE ""Books""
                SET ""AuthorId"" = (SELECT ""Id"" FROM ""Authors"" WHERE ""Name"" = 'Unknown Author' LIMIT 1)
                WHERE ""AuthorId"" IS NULL OR ""AuthorId"" = 0;
            ");

            // Make AuthorId NOT NULL
            migrationBuilder.Sql(@"
                ALTER TABLE ""Books"" 
                ALTER COLUMN ""AuthorId"" SET NOT NULL;
            ");

            // Create index if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Books_AuthorId"" ON ""Books"" (""AuthorId"");
            ");

            // Add foreign key constraint if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'FK_Books_Authors_AuthorId'
                    ) THEN
                        ALTER TABLE ""Books""
                        ADD CONSTRAINT ""FK_Books_Authors_AuthorId""
                        FOREIGN KEY (""AuthorId"") REFERENCES ""Authors"" (""Id"") ON DELETE RESTRICT;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Books_Authors_AuthorId",
                table: "Books");

            migrationBuilder.DropTable(
                name: "Authors");

            migrationBuilder.DropIndex(
                name: "IX_Books_AuthorId",
                table: "Books");

            migrationBuilder.DropColumn(
                name: "AuthorId",
                table: "Books");
        }
    }
}
